#!/bin/bash
#

set -x

DEV=$1
HOSTNAME=$2

if [ ! -w $DEV ]; then
   echo usage: $0 deviceFile hostname
   exit 1;
   fi

if [ "x$HOSTNAME" == "x" ]; then
   echo usage: $0 deviceFile hostname
   exit 1;
   fi
   
if [[ $DEV == *"mmcblk"* ]]; then
    PART1=${DEV}p1
    PART2=${DEV}p2
else
    PART1=${DEV}1
    PART2=${DEV}2
fi



dd if=/dev/zero of=$DEV bs=1024k count=10
sync

#Partition ...
# Units is SECTORS. 200MB = 409600
# 200MB FAT32 Boot
# Rest Root
#
sfdisk --delete $DEV
if ( $? -ne 0 ); then
    exit 1;
    fi

sfdisk $DEV   << EOF
,409600,c,*
;
EOF

if ( $? -ne 0 ); then
    exit 1;
    fi

#
# Now the Boot partition
#
mkfs.vfat -F32 -n BOOT ${PART1} || exit
mount ${PART1} /media/mnt || exit
tar -C /media/mnt -xvf BOOT.tar.bz2
sync
umount /media/mnt


#Now Root partition
mkfs.ext4 -L ROOT ${PART2} || exit
mount ${PART2} /media/mnt || exit
tar -C /media/mnt -xvf ROOT.tar.bz2
echo $HOSTNAME > /media/mnt/etc/hostname
rm -f /media/mnt/etc/ssh/*_key*
rm -f /media/mnt/var/cfengine/ppkeys/*
sync
umount /media/mnt

